Repository FACN3/rikaz, pull requests merged in 2018-02, with the labels that each got.

#17 initial set-up
  .babelrc
  .gitignore
  index.html
  package.json
  public/bundle.js
  src/index.js
  webpack.config.js
Labels: awaiting-review, priority-3

#15 basic readme
  README.md
Labels: awaiting-review

#19 creating the landing page
  index.html
  package.json
  public/assets/introductionBackground.png
  public/assets/logo.png
  public/assets/more-blue.png
  public/assets/smoke-512.ico
  public/bundle.js
  public/main.css
  src/components/App.js
  src/components/First_chart.js
  src/components/Landing_page.js
  src/components/ListButtons.js
  src/components/Main_button.js
  src/index.js
Labels: T4h, awaiting-review

#26 A copy of the last branch for merging
  .gitignore
  index.html
  package.json
  public/assets/left-arrow.png
  public/assets/person-solid.png
  public/assets/smoker.png
  public/main.css
  src/components/App.js
  src/components/First_chart.js
  src/components/First_chart_containers.js
  src/components/First_chart_figure.js
  src/components/Landing_page.js
  src/components/ListButtons.js
  src/components/List_buttons.js
  src/components/Main_button.js
  src/components/Smoking_page.js
  webpack.config.js
Labels: awaiting-review

#47 Set up the footer
  public/assets/footer-background.png
  public/main.css
  src/components/Footer.js
  src/components/Landing_page.js
  src/components/Smoking_page.js
Labels: awaiting-review

#57 Content and css
  public/assets/smoking-page-header.png
  public/main.css
  src/components/First_chart.js
  src/components/Landing_page.js
  src/components/Smoking_page.js
  src/components/chart_03/Third_Chart_Con.js
  src/components/chart_04/Fourth_Chart_Con.js
  src/components/time-series/TimeSeriesCon.js
  src/languages.js
Labels: awaiting-review
